---
- name: execute modprobe
  tags: tcp_bbr
  become: true
  modprobe:
    name: "{{ item }}"
    state: present
  loop: "{{ tcp_bbr_modules }}"

- name: reload sysctl
  tags: tcp_bbr
  become: true
  command: |
    sysctl -p {{ tcp_bbr_sysctl }}
...
